version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:6.2.6
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - 'redis_data:/bitnami/redis/data'
    ports:
      - "65001:6379"

  web:
    image: dfrpg2024-be-web
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6501:80"

  backend:
    image: dfrpg2024-be-1
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  redis_data:
    driver: local
